### ISSUE TITLE
Dead position not detected

### ISSUE THREAD

**Issue by ghost** [Uriopass/LCPlay#3]
8/8/2k5/1p2p2p/1P2P2P/8/5K2/8 b - - 0 34
I have reached dead position with Leela off.
The game was not terminated, but it must.

**Comment by Uriopass** [comment]
Why should it terminate ? Which rule says so ? I'm not sure what you mean

**Comment by ghost** [comment]
@Uriopass, neither player can checkmate. FIDE Laws of Chess
